language: python
cache: pip

matrix:
  include:
    - env: TOXENV=flake8
      python: 3.6
    - env: TOXENV=py27-dj18-wag18
      python: 2.7
    - env: TOXENV=py27-dj18-wag19
      python: 2.7
    - env: TOXENV=py27-dj18-wag110
      python: 2.7
    - env: TOXENV=py27-dj110-wag18
      python: 2.7
    - env: TOXENV=py27-dj110-wag19
      python: 2.7
    - env: TOXENV=py27-dj110-wag110
      python: 2.7
    - env: TOXENV=py27-dj111-wag18
      python: 2.7
    - env: TOXENV=py27-dj111-wag19
      python: 2.7
    - env: TOXENV=py27-dj111-wag110
      python: 2.7
    - env: TOXENV=py36-dj18-wag18
      python: 3.6
    - env: TOXENV=py36-dj18-wag19
      python: 3.6
    - env: TOXENV=py36-dj18-wag110
      python: 3.6
    - env: TOXENV=py36-dj110-wag18
      python: 3.6
    - env: TOXENV=py36-dj110-wag19
      python: 3.6
    - env: TOXENV=py36-dj110-wag110
      python: 3.6
    - env: TOXENV=py36-dj111-wag18
      python: 3.6
    - env: TOXENV=py36-dj111-wag19
      python: 3.6
    - env: TOXENV=py36-dj111-wag110
      python: 3.6

install:
  pip install tox coveralls

script:
  tox

after_success:
  coveralls
